version: '3'
services:
    sonar:
        build: ./sonar
        depends_on:
            - api
            - ui
            - proxy
    api:
        build:
          context: ./api
          args:
            # Token needed for the s2 structure service client package installation.
            # Get this from 1password (see README.md) and set it in a .env file.
            - GITHUB_ACCESS_TOKEN=$GITHUB_ACCESS_TOKEN
        volumes:
            - ./api:/usr/local/src/skiff/app/api
            - ./skiff_files/apps/pawls:/skiff_files/apps/pawls
        environment:
            # This ensures that errors are printed as they occur, which
            # makes debugging easier.
            - PYTHONUNBUFFERED=1
            - LOG_LEVEL=DEBUG
            - AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
            - AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
        command: ["main:app", "--host", "0.0.0.0", "--reload"]
    ui:
        build: ./ui
        # We can't mount the entire UI directory, since JavaScript dependencies
        # (`node_modules`) live at that location.
        volumes:
            - ./ui/src:/usr/local/src/skiff/app/ui/src
            - ./ui/public:/usr/local/src/skiff/app/ui/public
            - ./ui/package.json:/usr/local/src/skiff/app/ui/package.json
            - ./ui/tsconfig.json:/usr/local/src/skiff/app/ui/tsconfig.json
            - ./ui/yarn.lock:/usr/local/src/skiff/app/ui/yarn.lock
    proxy:
        build: ./proxy
        ports:
            - 8080:80
