version: '3'
services:
    sonar:
        build: ./sonar
        depends_on:
            - api
            - ui
            - proxy
    api:
        build:
            context: ./api
        volumes:
            # this enables auto-reload
            - ./api:/usr/local/src/skiff/app/api
            # location of skiff files
            - ./skiff_files/apps/pawls:/skiff_files/apps/pawls
            # list all allowed users (this is for local development,
            # in skiff this is passed in as a secret)
            - ./api/config/allowed_users_local_development.txt:/users/allowed.txt
            # mount aws credentials (with skiff they are passed as env
            # variables)
            #- $HOME/.aws/credentials:/root/.aws/credentials:ro
        environment:
            # This ensures that errors are printed as they occur, which
            # makes debugging easier.
            PYTHONUNBUFFERED: 1
            LOG_LEVEL: DEBUG
            # Import local variables for accessing aws buckets
            AWS_ACCESS_KEY_ID:
            AWS_SECRET_ACCESS_KEY:

        # needed to ensure being able to run mmda models over multiple
        # processes.
        shm_size: '4gb'
        command: ["main:app", "--host", "0.0.0.0", "--reload"]
    ui:
        build:
          context: ./ui
          dockerfile: Dockerfile-local
        # We can't mount the entire UI directory, since JavaScript dependencies
        # (`node_modules`) live at that location.
        volumes:
            - ./ui/src:/usr/local/src/skiff/app/ui/src
            - ./ui/public:/usr/local/src/skiff/app/ui/public
            - ./ui/package.json:/usr/local/src/skiff/app/ui/package.json
            - ./ui/tsconfig.json:/usr/local/src/skiff/app/ui/tsconfig.json
            - ./ui/yarn.lock:/usr/local/src/skiff/app/ui/yarn.lock
    proxy:
        build: ./proxy
        ports:
            - 8080:80
        depends_on:
            - api
            - ui
